var st1=new Stack<int>();
st1.Push(5);
st1.Push(10);
st1.Push(15);
st1.Push(20);
System.Console.WriteLine(st1.Peek());
System.Console.WriteLine("-----------------------------");
System.Console.WriteLine(st1.Pop());
System.Console.WriteLine("-----------------------------");
System.Console.WriteLine(st1.Peek());